### ISSUE TITLE
Adding a rule makes the defualt rules unable to assign to rulesets

### ISSUE THREAD

**Issue by Animeshz** [CharlotteDunois/Validator#5]
**Please describe the issue you are having:**
To add a rule `\CharlotteDunois\Validation\Validator::addRule($rule);`, we use this as per documentation but if it is executed before the validator is even once instanciated, then the default rules donot assign.

**If you are encountering any errors, post the full stack trace here:**
```
PHP Fatal error:  Uncaught RuntimeException: Validation Rule "class" does not exist in /home/animesh/Sites/TheIFan/vendor/charlottedunois/validator/src/Validator.php:133
Stack trace:
#0 /home/animesh/Sites/TheIFan/vendor/charlottedunois/validator/src/Validator.php(89): CharlotteDunois\Validation\Validator->startValidation()
#1 /home/animesh/Sites/TheIFan/src/test.php(12): CharlotteDunois\Validation\Validator->passes()
#2 {main}
  thrown in /home/animesh/Sites/TheIFan/vendor/charlottedunois/validator/src/Validator.php on line 133
```

**Please include a Minimal, Complete and Verifiable Example:**
```php
<?php

require __DIR__.'/../vendor/autoload.php';

$data = ['generator' => new \Animeshz\TheIFan\TheIFan];

\CharlotteDunois\Validation\Validator::addRule(new Animeshz\TheIFan\IFanRule);
$validator = CharlotteDunois\Validation\Validator::make($data, [
	'generator' => 'class:Animeshz\TheIFan\TheIFan'
]);

$validator->passes();
```
**Further details:**

Validator version: tested on https://github.com/CharlotteDunois/Validator/commit/97904c3284ac37856fb01038dc700d99bc343083

PHP version: PHP 7.2.10 (cli) (built: Sep 11 2018 07:06:00) ( NTS )

Operating System: tested on Fedora 28

**Comment by Animeshz** [comment]
could be fixed by changing https://github.com/CharlotteDunois/Validator/blob/master/src/Validator.php#L38 to check if a test rule(from Rules folder) is included in rulesets or not instead of checking if ruleset is empty.
